name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure the Python version matches your project's requirements

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git build-essential libssl-dev libffi-dev python3-dev
        sudo apt install -y openjdk-8-jdk
        pip install --upgrade pip
        pip install Cython==0.29.21 virtualenv
        pip install kivy

    - name: Set up Buildozer
      run: |
        pip install buildozer
        buildozer -v android debug

    - name: Build APK
      run: |
        buildozer android debug
        cp -r bin /home/runner/work/kitoki/project/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk
