name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools git build-essential libssl-dev libffi-dev python3-dev \
          openjdk-8-jdk \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
          libgstreamer1.0 libgstreamer-plugins-base1.0-dev libunwind-dev
        pip install --upgrade pip
        pip install Cython==0.29.21 virtualenv
        pip install kivy
        pip install PyMuPDF
        pip install kivy[uix]

    - name: Set up Buildozer
      run: |
        pip install buildozer
        sudo apt-get install -y liblzma-dev

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        cd $HOME/.buildozer/android/platform/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        rm -rf cmdline-tools  # Clean up the old directory structure
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Debug List of files in bin directory
      run: |
        ls -alh bin || echo "bin directory does not exist"

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug > buildozer.log 2>&1
        cat buildozer.log

    - name: Upload Buildozer Log
      uses: actions/upload-artifact@v3
      with:
        name: buildozer-log
        path: buildozer.log

    - name: Copy APK to workspace
      if: success()
      run: |
        if [ -d "bin" ]; then cp -r bin ${GITHUB_WORKSPACE}/project/bin; fi

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: ${GITHUB_WORKSPACE}/project/bin/*.apk
        if-no-files-found: warn
